CREATE TABLE hunts (
    id UUID PRIMARY KEY,
    repo_url TEXT NOT NULL,
    issues TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL,
    branch_name TEXT,
    diff_content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    report_md TEXT
);

CREATE TABLE logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hunt_id UUID NOT NULL REFERENCES hunts(id) ON DELETE CASCADE,
    log_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
